### PR TITLE
Optionally specify alternatives for uniqueness

### LINKED ISSUE #1635: Record uniqueness matcher fails with STI when type column is enum
### Description

The `succ` call described in https://github.com/thoughtbot/shoulda-matchers/issues/854 fails to match when the `type` column being used in STI is an enumerable, because that column's values are restricted.

### Reproduction Steps

Modify the below reproduction script to match a locally running Postgres install, and then run it.

```rb
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'shoulda-matchers'
  gem 'activerecord'
  gem 'pg'
  gem 'rspec'
end

require 'active_record'
require 'shoulda-matchers'
require 'logger'

ActiveRecord::Base.establish_connection(adapter: 'pg', database: 'YOUR_LOCATION_HERE')
ActiveRecord::Base.logger = Logger.new(STDOUT)

# TODO: Update the schema to include the specific tables or columns necessary
# to reproduct the bug
ActiveRecord::Schema.define do
  create_enum "big_model_types", ["BigModel", "LittleModel"]

  create_table :big_models, force: true do |t|
    t.enum "type", default: "BigModel", null: false, enum_type: "big_model_types"
  end

  create_table "model_fields", force: :cascade do |t|
    t.string "name", null: false
    t.string "record_type", null: false
    t.bigint "record_id", null: false
  end
end

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec

    with.library :active_record
    with.library :active_model
  end
end

RSpec.configure do |config|
  config.include Shoulda::Matchers::ActiveRecord
  config.include Shoulda::Matchers::ActiveModel
  config.include Shoulda::Matchers::ActionController
end

# TODO: Add any application specific code necessary to reproduce the bug
class BigModel < ActiveRecord::Base
  has_one :some_model_field,
          -> { where(name: 'some') },
          as: :record,
          autosave: true,
          class_name: 'ModelField',
          dependent: :destroy,
          inverse_of: :record
end

class ModelField < ActiveRecord::Base
  belongs_to :record, polymorphic: true, optional: false

  validates :name, presence: true, uniqueness: {scope: [:record_id, :record_type]}
end

# typed: false
FactoryBot.define do
  factory :model_field do
    name { "my_field_name" }
  end
end

# TODO: Write a failing test case to demonstrate what isn't working as
# expected
RSpec.describe ModelField do
  describe "name + record uniqueness" do
    subject { build(:model_field, record: nil) }

    before { create(:model_field, record: nil) }

    let(:record) { create(:big_model) }

    it { is_expected.to validate_uniqueness_of(:name).scoped_to([:record_id, :record_type]) }
  end
end


```

### Expected behavior

Validation passes.

### Actual behavior

```
1) ModelField validations name + record uniqueness is expected to validate that :name is case-sensitively unique within the scope of :record_id and :record_type
     Failure/Error: it { is_expected.to validate_uniqueness_of(:name).scoped_to([:record_id, :record_type]) }

     ActiveRecord::StatementInvalid:
       PG::InvalidTextRepresentation: ERROR:  invalid input value for enum big_model_types: "Shoulda::Matchers::ActiveRecord::Uniqueness::TestModels::BigModem"
       LINE 1: ...g_models" WHERE "big_models"."type" = 'Shoulda::...
                                                                    ^
     # ./spec/models/model_field_spec.rb:17:in `block (4 levels) in <main>'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # PG::InvalidTextRepresentation:
     #   ERROR:  invalid input value for enum big_model_types: "Shoulda::Matchers::ActiveRecord::Uniqueness::TestModels::BigModem"
     #   LINE 1: ...g_models" WHERE "big_models"."type" = 'Shoulda::...
     #                                                                ^
     #   ./spec/models/model_field_spec.rb:17:in `block (4 levels) in <main>'
```

### System configuration
**shoulda_matchers version**: 6.2.0
**rails version**: 7.1.3.2
**ruby version**: 3.2.1

### PR DESCRIPTION
**Pull request by lake-effect**
Resolves #1635. 

This adds an `.alternatives` option to specify alternatives the uniqueness matcher should use to test with if constraints don't allow for freeform alternatives in the column (such as enumerable columns, STI constrained type columns, etc.)

### CODE REVIEW

File: lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb [hunk 1]
```diff
@@ -836,6 +879,10 @@ def next_scalar_value_for(scope, previous_value)
             available_values.keys.last
           elsif polymorphic_type_attribute?(scope, previous_value)
             Uniqueness::TestModels.create(previous_value).to_s
+          elsif @options[:alternatives] && scope == @attribute
+            alternatives = @options[:alternatives]
```
Comment (matsales28) [inline lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:883]: We could simplify the alternatives assignment using the `Array#wrap` method.
```suggestion
            alternatives = Array.wrap(@options[:alternatives])
```

File: lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb [hunk 2]
```diff
@@ -258,6 +258,35 @@ module ActiveRecord
       #
       # @return [ValidateUniquenessOfMatcher]
       #
+      # ##### alternatives
+      #
+      # Use `alternatives` to specify alternative values to use for testing uniqueness.
```
Comment (matsales28) [inline lib/shoulda/matchers/active_record/validate_uniqueness_of_matcher.rb:263]:
```suggestion
      # Use `alternatives` to specify alternative valid values to use for testing uniqueness.
```

**Review by matsales28 — COMMENTED** [review]
I left a couple minor suggestions, besides that it looks good to me! Thanks for working on that.

**Comment by matsales28** [comment]
@lake-effect there are a couple of rubocop failures as well, please take a look at https://github.com/thoughtbot/shoulda-matchers/actions/runs/14000477189/job/39301628329?pr=1664

**Comment by lake-effect** [comment]
Hi @matsales28, is there anything else we should look at here? Rubocop should be passing now.

**Comment by matsales28** [comment]
> Hi @matsales28, is there anything else we should look at here? Rubocop should be passing now.

@lake-effect None that I can think of. Rerunning the CI, gonna merge if green. Thanks again for your work on this.

**Comment by carlosramireziii** [comment]
@matsales28 Thank you for merging this! 

Do you think this new feature warrants a new gem version release (last release was Aug 2024)? There are a couple of new features (including this one) that would be included. Any sense for the timeline on that? 

Happy to help in whatever way I can. Thanks again!

**Comment by fabn** [comment]
Waiting for release as well 🙏

**Comment by matsales28** [comment]
@carlosramireziii @fabn, I'll try to make a new release this week.

**Comment by matsales28** [comment]
@carlosramireziii @fabn  the new version was released, sorry for the delay!

**Comment by JGefroh** [comment]
Thank you! 🥳

**Comment by carlosramireziii** [comment]
No apologies necessary, thank you for getting this out! 🎉
